version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

  backend:
    build: ./trading-bot-backend
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COINBASE_API_KEY=<your_coinbase_api_key>
      - COINBASE_SECRET=<your_coinbase_secret_key>
      - BINANCE_API_KEY=<your_binance_api_key>
      - BINANCE_SECRET=<your_binance_secret_key>
      - COINMARKETCAP_API_KEY=<your_coinmarketcap_api_key>

  frontend:
    build: ./my-trading-bot-frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
